# Generated by Django 5.1.5 on 2025-03-05 12:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('MaLoai', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã loại')),
                ('TenLoai', models.CharField(max_length=50, verbose_name='Tên loại')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('MoTa', models.TextField(blank=True, verbose_name='Mô tả')),
                ('TrangThai', models.SmallIntegerField(choices=[(1, 'Hiện'), (0, 'Ẩn')], default=1, verbose_name='Trạng thái')),
                ('NgayTao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('NgayCapNhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('MaNCC', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã NCC')),
                ('TenNCC', models.CharField(max_length=50, verbose_name='Tên NCC')),
                ('DiaChi', models.CharField(max_length=100, verbose_name='Địa chỉ')),
                ('SoDienThoai', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('Email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('TrangThai', models.SmallIntegerField(choices=[(1, 'Hiện'), (0, 'Ẩn')], default=1, verbose_name='Trạng thái')),
            ],
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiaChi', models.CharField(max_length=100, verbose_name='Địa chỉ')),
                ('SoDienThoai', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Số điện thoại')),
                ('NgaySinh', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='Ảnh đại diện')),
                ('VaiTro', models.CharField(choices=[('1', 'Admin'), ('2', 'Nhân viên'), ('3', 'Khách hàng')], default='3', max_length=1, verbose_name='Vai trò')),
                ('NgayDangKy', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('TrangThai', models.SmallIntegerField(choices=[(1, 'Hiện'), (0, 'Ẩn')], default=1, verbose_name='Trạng thái')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('MaHD', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã hóa đơn')),
                ('NgayDat', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt')),
                ('TrangThai', models.CharField(choices=[('1', 'Chờ xác nhận'), ('2', 'Đang giao'), ('3', 'Đã giao'), ('4', 'Hủy')], default='1', max_length=20, verbose_name='Trạng thái')),
                ('DiaChiGiao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ giao')),
                ('SDTGiao', models.CharField(blank=True, max_length=15, null=True, verbose_name='SĐT giao hàng')),
                ('PhuongThucThanhToan', models.CharField(choices=[('1', 'Tiền mặt'), ('2', 'Chuyển khoản'), ('3', 'Ví điện tử')], default='1', max_length=1, verbose_name='Phương thức thanh toán')),
                ('GhiChu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('NguoiDat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.nguoidung', verbose_name='Người đặt')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('MaSP', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã sản phẩm')),
                ('TenSP', models.CharField(max_length=50, verbose_name='Tên sản phẩm')),
                ('DonGia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá')),
                ('HinhAnh', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Hình ảnh')),
                ('MoTa', models.TextField(blank=True, verbose_name='Mô tả')),
                ('SoLuong', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng')),
                ('GiamGia', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Giảm giá (%)')),
                ('DonViTinh', models.CharField(default='Cái', max_length=20, verbose_name='Đơn vị tính')),
                ('TrangThai', models.SmallIntegerField(choices=[(1, 'Hiện'), (0, 'Ẩn')], default=1, verbose_name='Trạng thái')),
                ('NgayNhapKho', models.DateTimeField(auto_now_add=True, verbose_name='Ngày nhập kho')),
                ('HanSuDung', models.DateField(blank=True, null=True, verbose_name='Hạn sử dụng')),
                ('LoaiSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.loaisanpham', verbose_name='Loại sản phẩm')),
                ('NCC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.nhacungcap', verbose_name='Nhà cung cấp')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NgayThayDoi', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thay đổi')),
                ('SoLuong', models.IntegerField(verbose_name='Số lượng')),
                ('LoaiThayDoi', models.CharField(choices=[('1', 'Nhập'), ('2', 'Xuất')], max_length=1, verbose_name='Loại thay đổi')),
                ('GhiChu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('NguoiThucHien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.nguoidung', verbose_name='Người thực hiện')),
                ('SanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sanpham', verbose_name='Sản phẩm')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuong', models.IntegerField(verbose_name='Số lượng')),
                ('DonGia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá')),
                ('MaHD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.hoadon', verbose_name='Hóa đơn')),
                ('MaSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.sanpham', verbose_name='Sản phẩm')),
            ],
        ),
    ]
